# Generated by Django 5.2.17 on 2026-09-02 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AwsConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("aws_account_id", models.CharField(max_length=12)),
                ("default_region", models.CharField(max_length=32)),
                (
                    "authentication_method",
                    models.CharField(
                        choices=[
                            ("IAM_ROLE", "IAM role"),
                            ("DEVELOPMENT", "Development placeholder"),
                        ],
                        default="DEVELOPMENT",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Unverified"),
                            ("ACTIVE", "Active"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="UNVERIFIED",
                        max_length=16,
                    ),
                ),
                ("created_by_user_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
